name: python_x509_pkcs11-centos

on: [push]

jobs:
  container-test-job:

    runs-on: ubuntu-latest
    container: quay.io/centos/centos:stream9
    steps:
      - name: Install dependencies
        run: |
          dnf install git python3-devel python3-pip softhsm gcc sudo -y
          useradd python_x509_pkcs11 -m
          usermod -a -G ods python_x509_pkcs11
          sudo -u python_x509_pkcs11 bash -c 'export PATH="$PATH:$HOME/.local/bin" && id && cd && git clone https://github.com/SUNET/python_x509_pkcs11.git && cd python_x509_pkcs11 && pip3 install mypy black pylint flit && python3 -m pip install -r requirements.txt && bash dev-run.sh && flit build && pip3 install dist/python_x509_pkcs11*.whl'
